### ISSUE TITLE
Statische Daten, immer 25ug/m³

### ISSUE THREAD

**Issue by muckisg** [MakeMagazinDE/vindriktning2adafruitio#1]
Hallo,

im Sourcecode wird ein fester Wert von 25 gesetzt, für Anfäger ggf. problematisch, wenn diese den Fehler in der Schaltung suchen. :-)
Ich würde den Code wie folgt weiter geben:
 
// Sensor abfragen
spm25 = getSensorData();

Hope it helps,

Maurice

**Comment by MakeMagazinDE** [comment]
Ist wie im Forum gesagt korrigiert, da hatte sich eine Testversion reingeschummelt...
